### ISSUE TITLE
Stop storing secrets in state/plan files

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-vault#160]
I was evaluating using the terraform provider for vault vs ansible's hashivault (https://github.com/TerryHowe/ansible-modules-hashivault) to manage vault configuration and secrets. 

The information block in https://www.terraform.io/docs/providers/vault/index.html says:

```
Important Interacting with Vault from Terraform causes any secrets that you read and write to be
persisted in both Terraform's state file and in any generated plan files. For any Terraform module that
reads or writes Vault secrets, these files should be treated as sensitive and protected accordingly.
```

If I've understood this correctly, I find this very alarming (isn't it a fundamental security principle to minimise the number of places secrets are available?). It seems like its negating the point of vault - to have a single highly available place where secrets can be read and audited. Instead there are multiple places the secrets end up being written down, and some you have to provide your own mechanisms to audit (the statefile and local planfiles, which therefore means all admin computers etc.). Lots of compliance audits fail you if you have secrets written down in files in plaintext anywhere. 

I feel it should be possible if storing the secrets to store a secure hashed version of them at least, which whilst not perfect, would offer at least some protection whilst still being able to detect changes, or better still not actually store them at all, but probably this makes the workflow awkward because terraform will always claim to change them.

Is there any way around this, do you see it as a limitation of terraform currently? As it stands it would seem that ansible-hashivault plus "ansible vault" at least means I can manage vault secrets with them only being written in vault, which seems a clear advantage. 

Thanks!

**Comment by tyrannosaurus-becks** [comment]
@gtmtech I think all the points you make are excellent, and we may be moving away from this feature in the future for the exact reasons you give.

I haven't tested this yet, but there _may_ be a way around it. If you _don't_ feed in secrets via the Terraform config file, they _may_ not come out in the state file. Taking this approach, you'd add them via a different method, such as using the Vault UI or API. The secrets would ultimately be stored in your configured storage engine in their normal encrypted format.

Many such storage engines support backups or snapshots, and Vault also has replication features, so you'd rely on that sort of thing to back up your secrets rather than the Terraform state file.

**Comment by tyrannosaurus-becks** [comment]
After playing with the code, I learned that I won't be able to effect how state is stored within the Terraform Vault Provider because it's just a provider for Terraform, and _Terraform_ drives how state is stored. 

I also found that the Amazon S3 Terraform back end can be used to encrypt state, in that S3 buckets can be encrypted. https://www.terraform.io/docs/backends/types/s3.html.

Closing this ticket because it's not addressable here. Thank you!
