### ISSUE TITLE
Upstream Vault Provider BC change means 1.3.x should have been 2.x

### ISSUE THREAD

**Issue by lattwood** [terraform-providers/terraform-provider-vault#233]
Because of this change in the upstream vault API this provider needs to have 1.3.x withdrawn and a 2.x release made, sadly: https://github.com/hashicorp/vault/pull/5583#issuecomment-433917566

Related issue: https://github.com/terraform-providers/terraform-provider-vault/issues/229

**Comment by tyrannosaurus-becks** [comment]
Hi! Thank you for pointing this out!

We don't tend to base the versioning in this provider off the upstream repo. We're following the best practices for extending Terraform discussed [here](https://www.terraform.io/docs/extend/best-practices/versioning.html), which is mainly based on the flow of the provider's schema fields. This is the behavior expected by most users, because 1) they could be pointing the provider at any version of Vault, and 2) they tend to account for the provider's behavior that way when configuring [acceptable versions](https://www.terraform.io/docs/configuration/providers.html#version-provider-versions) of it to use.

We will definitely release a new major version next time we deprecate any fields in the provider though! Thanks again!
