### ISSUE TITLE
Provider Should Support Vault Token Helpers

### ISSUE THREAD

**Issue by icebourg** [terraform-providers/terraform-provider-vault#41]
Vault has support for something called [token helpers](https://www.vaultproject.io/docs/commands/token-helper.html) which are invaluable if you run many different Vault clusters. The provider should support these so that we don't have to re-implement the idea in every use of Terraform + Vault.

**Comment by apparentlymart** [comment]
Hi @icebourg! Thanks for this feature request.

Indeed it would be great to support token helpers, and to automatically discover them in the `~/.vault` file as the Vault CLI does.

Unfortunately currently token helpers are implemented directly in the Vault CLI code rather than in the Vault API code we currently depend on for this provider. In principle we could access [the `DefaultTokenHelper` function](https://godoc.org/github.com/hashicorp/vault/command#DefaultTokenHelper) exported in Vault's `command` package to replicate the CLI functionality, but first we ought to confer with the Vault team about whether they consider that a public interface that other software should depend on.

**Comment by paddycarver** [comment]
As of hashicorp/vault#4055, these should now be broken out into an easier-to-import package.

**Comment by lawliet89** [comment]
This is already fixed in https://github.com/terraform-providers/terraform-provider-vault/pull/136

**Comment by lawliet89** [comment]
@tyrannosaurus-becks This is already fixed in https://github.com/terraform-providers/terraform-provider-vault/pull/136

**Comment by tyrannosaurus-becks** [comment]
Thanks @lawliet89!
