### ISSUE TITLE
no resource like vault_gcp_login, can't authenticate to vault from gcp

### ISSUE THREAD

**Issue by yanan-xu** [terraform-providers/terraform-provider-vault#519]
resource `vault_aws_auth_backend_login` used to log into a Vault server using an AWS auth backend. but gcp can't

**Comment by yanan-xu** [comment]
I have enabled GCP auth method in Vault server, and configured the GCP service account key json file in Vault.
Now I want to using this service account auth to Vault in terraform. Is it possible to approach?

**Comment by mengesb** [comment]
The following might be helpful if you're configuring the vault provider to use GCP auth

- https://www.terraform.io/docs/providers/vault/#example-auth_login-usage
- https://www.vaultproject.io/api-docs/auth/gcp#login

```hcl
provider "vault" {
  address = var.address

  auth_login {
    path = "auth/gcp/login"

    parameters = {
      role = var.role
      jwt  = var.jwt
    }
  }
}
```

**Comment by yanan-xu** [comment]
thanks @mengesb , this may take me a while to remember, I haven't written terraform for several months. 
but from the block, we have to hard code jwt?

**Comment by mengesb** [comment]
in the case of TFE/Cloud, it can be a sensitive variable. In the case of TF OSS, you can make it a privately held `auto.tfvars` that's not committed to the repo. Otherwise you need to collect some level of information from the metadata service potentially.

we use the `auth_login` block method for AWS presently, instead of using the resource which requires you to have the provider configured to use.

**Comment by yanan-xu** [comment]
we're using TF OSS, `auto.tfvars` should be a good solution to prevent exposure of such sensitive variable. thanks for your direction.
