### ISSUE TITLE
Deploying Vault policies/configurations via Terraform fails on many endpoints.

### ISSUE THREAD

**Issue by draggeta** [terraform-providers/terraform-provider-vault#52]
### Terraform Version
Terraform v0.11.1

### Affected Resource(s)
All Terraform Vault actions

### Terraform Configuration Files
```hcl
resource "vault_generic_secret" "audit_file" {
  path = "sys/audit/file"

  data_json = <<EOT
{
  "type": "file",
  "options": {
      "path": "F:/HashiCorp/Vault/vault.audit/audit.log"
  }
}
EOT
}
```

### Expected Behavior
It should create the audit configuration

### Actual Behavior
It throws an error:
```powershell
C:\> terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

vault_generic_secret.audit_file: Refreshing state... (ID: sys/audit/file)

Error: Error refreshing state: 1 error(s) occurred:

* vault_generic_secret.audit_file: 1 error(s) occurred:

* vault_generic_secret.audit_file: vault_generic_secret.audit_file: error reading from Vault: Error making API request.

URL: GET https://vault.domain.com:8200/v1/sys/audit/file
Code: 405. Errors:

* 1 error occurred:

* unsupported operation
```

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` or `terraform plan`

### Important Factoids
Seems to be related to the fact that not all HTTP verbs are accepted anymore.

**Comment by draggeta** [comment]
This may be a better example:
```hcl
# Configure the Consul master token used by Vault
resource "vault_generic_secret" "consul_config" {
  path = "consul/config/access"

  data_json = <<EOT
    {
      "address": "127.0.0.1:8500",
      "scheme": "http",
      "token": "a60178da-1faa-49bc-b234-ffaca29719af"
    }
EOT
}
```
gives the following error

```
Error: Error applying plan:

1 error(s) occurred:

* vault_generic_secret.consul_config: 1 error(s) occurred:

* vault_generic_secret.consul_config: error writing to Vault: Error making API request.

URL: PUT https://vault.ogd.nl:8200/v1/consul/config/access
Code: 404. Errors:

* no handler for route 'consul/config/access'
```

**Comment by apparentlymart** [comment]
Hi @draggeta! Sorry for the problems here.

The `vault_generic_secret` resource was originally designed only for writing to [the Key/Value secret backend](https://www.vaultproject.io/docs/secrets/kv/index.html) (formerly known as the "Generic" secret backend) and that it happens to also be able to write to other endpoints is more of an accident of Vault's design than a goal. Unfortunately it's not compatible with all endpoints because, as you've seen, some have additional constraints beyond what is expected for the Key/Value backend, and indeed Vault now distinguishes between `PUT` and `POST` in many cases, further limiting this flexibility.

A key problem this provider faces is that Vault's API is very dynamic -- any endpoint can accept and return any arbitrary JSON in principle -- but Terraform is designed around the idea of a static, strongly-typed schema so that it is able to validate configuration locally. As a result, we've implemented some specialized resource types and data sources to interact with endpoints exposed by different backends, but so far haven't implemented any for [the Consul backend](https://www.vaultproject.io/api/secret/consul/index.html).

Given the above, I think the resolution of this issue would be to implement a `vault_consul_secret_backend` resource that is an analog to [`vault_aws_secret_backend`](https://www.terraform.io/docs/providers/vault/r/aws_secret_backend.html), and likewise `vault_consul_secret_backend_role` to correspond with [`vault_aws_secret_backend_role`](https://www.terraform.io/docs/providers/vault/r/aws_secret_backend_role.html), and possibly other specialized resources for the other endpoints supported by this secret backend.

Unfortunately the Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.

**Comment by draggeta** [comment]
The consule backend has been fixed and audit has also been enabled, so this can be closed.
