### ISSUE TITLE
Unable to run `terraform destroy` when configuring `okta` auth backend

### ISSUE THREAD

**Issue by wjam** [terraform-providers/terraform-provider-vault#7]
Not all Vault endpoints support delete which means that if you try and set up a Vault instance using `vault_generic_secret`, such as the example below, you won't be able to successfully run `terraform destroy`. 
```hcl
resource "vault_auth_backend" "example" {
  type = "okta"
}

resource "vault_generic_secret" "example" {
  path = "auth/${vault_auth_backend.example.path}/config"
  data_json = <<EOT
{
}
EOT
}
```

The Vault team are reluctant to go through all of the endpoints to add delete (https://github.com/hashicorp/vault/pull/2889) but the way the Vault provider currently works prevents them from being properly.

One solution I thought of would be to move away from generic `vault_auth_backend` to ones specific to each auth backend or mount. The advantage that this approach has is that it avoids having to look up API endpoints to know how to configure an auth backend and helps stop `vault_generic_secret` from being used as a hammer for all of the problems.

Opinion?

**Comment by usererror** [comment]
@wjam Not sure if you're still looking for a solution here but I ran into the same _exact_ problem with github auth. One pure tf solution that currently works is to use a null resource to do the configuration instead of a `vault_generic_secret` directly:

```hcl
# main.tf of a module called null-write i use to get around this issue
resource "null_resource" "config" {
  triggers = {
    path = "${var.path}"
    data = "${var.data}"
  }

  provisioner "local-exec" {
    command = "echo '${var.data}' | vault write ${var.path} -"
  }
}
```

which you would use like (the data must be json, you can use the builtin jsonencode function along with the builtin list/map funcs to build the data properly)...

```hcl
# main.tf of a module using the null-write module to configure an auth backend
resource "vault_auth_backend" "backend" {
  type        = "${var.type}"
  path        = "${var.path}"
  description = "${var.description}"
}

# you could repeat this block numerous times to create multiple approle roles etc.
module "config" {
  source = "../null-write"
  
  path = "${var.config_path}"
  data = "${var.config_data}"
}
```

Unfortunately this is much less obvious than using the generic secret resource and many people are unfamiliar with null_resource. It would be nice if we could configure the auth backends directly in a cleaner way. It really comes down to just writing json data to a path, but some auth backends like `approle` may require more than one k=v configuration (multiple roles for example).
