### ISSUE TITLE
AWS secret backend nested path support

### ISSUE THREAD

**Issue by lmickh** [terraform-providers/terraform-provider-vault#78]
Hi there,

### Terraform Version
v0.11.3

### Affected Resource(s)
vault_aws_secret_backend_role

### Terraform Configuration Files
```
resource "vault_aws_secret_backend" "nested-aws-path" {
  access_key                = "${var.access_key}"
  secret_key                = "${var.secret_key}"
  path                      = "nested/aws/path"
 <snip>
}

resource "vault_aws_secret_backend_role" "admin" {
  backend = "${vault_aws_secret_backend.nested-aws-path.path}"
  name    = "admin"

  policy_arn = "arn:aws:iam::aws:policy/AdministratorAccess"
}
```

### Expected Behavior
`nested/aws/path` is a valid mount point.  I expect it to create `nested/aws/path/roles/admin`.  This can be done via the Vault CLI.

### Actual Behavior
TF fails providing the following error:
`Invalid id nested/aws/path/roles/admin; must be {backend}/roles/{name}`

### Steps to Reproduce

1. `terraform apply`

**Comment by martinssipenko** [comment]
I think there is a related bug.

I was able to create a role ins nested path (i see it in my `vault list aws/nested/roles` output), but Terraform reported the same error.

Looking at code I think this happens because check is performed in `awsSecretBackendRoleRead` func, which is called only after the resource has been created (at the end of `awsSecretBackendRoleWrite`). Further, running terraform plan (which uses the `awsSecretBackendRoleRead` func) it triggers that error.

**Comment by lmickh** [comment]
It is resolved.  Closing it.
